services:
  postgres:
    image: postgres:latest
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 111111
      POSTGRES_DB: postgres
    volumes:
      - simple-chat-postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: simple-chat-redis
    expose:
      - '6379'
    ports:
      - '6380:6379' # increase port number if you already have redis running on your machine

volumes:
  simple-chat-postgres-data:
